-- 20260804_bug_status_portal.sql
-- Bug Status Portal — the return path. Reporters see what happened to the bugs
-- they filed, and exchange notes with the dev team, from inside any application
-- registered on the platform.
--
-- Additive only: CREATE ... IF NOT EXISTS, ADD COLUMN IF NOT EXISTS, DROP NOT NULL
-- (idempotent), new policies/functions. No data mutation, no destructive drops.
-- Isolation mirrors the `applications` table's org-membership RLS.
--
-- Decisions (locked): the feature is per-application opt-in and starts OFF;
-- status stays owned by the dashboard (client apps get read + notes only);
-- reporters are identified by metadata->>'reporter_email'; webhook rows are
-- written only by service-role, but readable by org members for the settings UI.

-- ── 0. reconcile schema drift ────────────────────────────────────────────────
-- `reporter_user_id` was made nullable by hand in production (see
-- docs/ISSUE_FIXED_reporter_user_id.md) with no migration file — SDK submissions
-- are anonymous and carry no auth.users row. Codify it so the repo SQL and the
-- live database finally agree. Safe to re-run: dropping NOT NULL twice is a no-op.
ALTER TABLE public.bug_reports
  ALTER COLUMN reporter_user_id DROP NOT NULL;

-- Same problem, one table over: system-generated and reporter-authored notes have
-- no auth.users row. Today `sender_user_id: null` inserts fail against the NOT NULL
-- constraint — silently, because the insert is never error-checked. See
-- app/api/v1/public/bug-reports/[id]/route.ts.
ALTER TABLE public.bug_report_messages
  ALTER COLUMN sender_user_id DROP NOT NULL;

-- ── 1. note authorship ───────────────────────────────────────────────────────
-- Who wrote a note, when there may be no auth.users row to point at.
--   user      — an authenticated platform user (the historical default)
--   developer — a dev replying from the dashboard
--   reporter  — the person who filed the bug, via the portal / public API
--   system    — generated by a status change
ALTER TABLE public.bug_report_messages
  ADD COLUMN IF NOT EXISTS author_kind text NOT NULL DEFAULT 'user';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'bug_report_messages_author_kind_check'
  ) THEN
    ALTER TABLE public.bug_report_messages
      ADD CONSTRAINT bug_report_messages_author_kind_check
      CHECK (author_kind IN ('user', 'developer', 'reporter', 'system'));
  END IF;
END $$;

-- Identifies a reporter who has no auth.users row.
ALTER TABLE public.bug_report_messages
  ADD COLUMN IF NOT EXISTS author_email text;

-- NOTE: message attachments already live in `bug_report_message_attachments`
-- (and reactions in `bug_report_message_metadata`). Both tables exist in the
-- database but are absent from this repo's migration history, so the repo SQL
-- alone does not describe production. They are deliberately NOT duplicated into
-- a JSONB column here — one source of truth per fact.

-- ── 2. the portal's scoping key ──────────────────────────────────────────────
-- Reporter identity lives in metadata JSONB, so it can't be indexed or joined
-- efficiently and every consumer re-derives it differently. A STORED generated
-- column fixes that for every existing and future row with no backfill and no
-- possibility of drifting out of sync with metadata.
--
-- This column is what makes "show me only MY bugs" a single indexed equality
-- rather than a scan — and closes the /me leak, where the absence of any
-- per-reporter filter returned every reporter's bugs to every user of an app.
--
-- Kept as a plain column maintained by a trigger, NOT a GENERATED ... STORED
-- column. A stored generated column forces a full table rewrite, which rebuilds
-- every index on bug_reports — including the ivfflat vector index on
-- `embedding` (vector(1536), lists=100). That rebuild needs ~61 MB against this
-- instance's 32 MB maintenance_work_mem and fails outright. Adding a nullable
-- column with no default is metadata-only in Postgres 11+, so the vector index
-- is never touched.
ALTER TABLE public.bug_reports
  ADD COLUMN IF NOT EXISTS reporter_email text;

CREATE OR REPLACE FUNCTION public.fn_sync_bug_reporter_email()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public AS $$
BEGIN
  NEW.reporter_email := lower(nullif(trim(NEW.metadata->>'reporter_email'), ''));
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_bug_reporter_email ON public.bug_reports;
CREATE TRIGGER set_bug_reporter_email
  BEFORE INSERT OR UPDATE OF metadata ON public.bug_reports
  FOR EACH ROW EXECUTE FUNCTION public.fn_sync_bug_reporter_email();

-- Backfill existing rows. Small (hundreds of rows) and idempotent.
UPDATE public.bug_reports
   SET reporter_email = lower(nullif(trim(metadata->>'reporter_email'), ''))
 WHERE reporter_email IS DISTINCT FROM
       lower(nullif(trim(metadata->>'reporter_email'), ''));

-- Composite: every portal query is scoped by BOTH app and reporter. Never one
-- without the other — a single-column index here would invite exactly the
-- cross-tenant mistake this feature has to avoid.
CREATE INDEX IF NOT EXISTS idx_bug_reports_app_reporter
  ON public.bug_reports (application_id, reporter_email);

-- ── 3. status history ────────────────────────────────────────────────────────
-- Status is currently a destructive in-place UPDATE: the previous value and the
-- actor are lost forever. The portal needs a timeline, and "who changed this and
-- why" is the first question anyone asks about a bug.
CREATE TABLE IF NOT EXISTS public.bug_status_events (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  bug_report_id    uuid NOT NULL REFERENCES public.bug_reports(id) ON DELETE CASCADE,
  organization_id  uuid NOT NULL,   -- denormalized for RLS (avoids a join per row)
  application_id   uuid NOT NULL,   -- denormalized for tenant-scoped queries
  from_status      text,            -- NULL for the synthetic "created" event
  to_status        text NOT NULL,
  note             text,
  actor_kind       text NOT NULL DEFAULT 'system',
  actor_user_id    uuid,            -- set when actor_kind = 'dashboard_user'
  actor_label      text,            -- display name / app name, denormalized
  created_at       timestamptz NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'bug_status_events_actor_kind_check'
  ) THEN
    ALTER TABLE public.bug_status_events
      ADD CONSTRAINT bug_status_events_actor_kind_check
      CHECK (actor_kind IN ('dashboard_user', 'api_key', 'system'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS bug_status_events_bug_idx
  ON public.bug_status_events (bug_report_id, created_at DESC);
CREATE INDEX IF NOT EXISTS bug_status_events_app_idx
  ON public.bug_status_events (application_id, created_at DESC);

-- ── 4. webhook delivery queue ────────────────────────────────────────────────
-- `applications.settings.webhook_url` has been collected in the UI since the
-- applications module shipped, with the promise "Receive notifications when new
-- bugs are reported" — and nothing has ever delivered to it. This is the queue
-- that finally does. Modelled on app_ai_routine_runs.
CREATE TABLE IF NOT EXISTS public.webhook_deliveries (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id  uuid NOT NULL,   -- denormalized for RLS
  application_id   uuid NOT NULL REFERENCES public.applications(id) ON DELETE CASCADE,
  bug_report_id    uuid REFERENCES public.bug_reports(id) ON DELETE SET NULL,
  event_type       text NOT NULL,   -- bug.status_changed | bug.note_added
  payload          jsonb NOT NULL,
  target_url       text NOT NULL,   -- snapshotted at enqueue time
  status           text NOT NULL DEFAULT 'queued',  -- queued | delivering | done | error
  attempts         int  NOT NULL DEFAULT 0,
  next_attempt_at  timestamptz NOT NULL DEFAULT now(),
  response_status  int,
  last_error       text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  delivered_at     timestamptz
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'webhook_deliveries_status_check'
  ) THEN
    ALTER TABLE public.webhook_deliveries
      ADD CONSTRAINT webhook_deliveries_status_check
      CHECK (status IN ('queued', 'delivering', 'done', 'error'));
  END IF;
END $$;

-- Partial index: the dispatcher only ever looks at pending work, and this keeps
-- that lookup cheap no matter how much delivered history accumulates.
CREATE INDEX IF NOT EXISTS webhook_deliveries_due_idx
  ON public.webhook_deliveries (next_attempt_at)
  WHERE status IN ('queued', 'delivering');
CREATE INDEX IF NOT EXISTS webhook_deliveries_app_idx
  ON public.webhook_deliveries (application_id, created_at DESC);

-- ── 5. RLS — read = org members; writes = service-role only ──────────────────
ALTER TABLE public.bug_status_events  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.webhook_deliveries ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'bug_status_events'
      AND policyname = 'bug_status_events_read'
  ) THEN
    CREATE POLICY bug_status_events_read ON public.bug_status_events
      FOR SELECT USING (
        EXISTS (SELECT 1 FROM public.super_admins s WHERE s.user_id = auth.uid())
        OR organization_id IN (
          SELECT m.organization_id FROM public.organization_members m
          WHERE m.user_id = auth.uid()
        )
      );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'webhook_deliveries'
      AND policyname = 'webhook_deliveries_read'
  ) THEN
    -- Readable so the app Settings card can show recent deliveries and the last
    -- error. A webhook that fails silently is worse than no webhook at all.
    -- No INSERT/UPDATE policy exists: only the service-role dispatcher writes here.
    CREATE POLICY webhook_deliveries_read ON public.webhook_deliveries
      FOR SELECT USING (
        EXISTS (SELECT 1 FROM public.super_admins s WHERE s.user_id = auth.uid())
        OR organization_id IN (
          SELECT m.organization_id FROM public.organization_members m
          WHERE m.user_id = auth.uid()
        )
      );
  END IF;
END $$;

-- ── 6. dispatcher RPC (SECURITY DEFINER, service-role only) ──────────────────
-- Atomically CLAIM due deliveries with UPDATE ... RETURNING, so two overlapping
-- cron invocations can't both send the same webhook. A plain SELECT-then-UPDATE
-- would double-fire under exactly the conditions serverless crons create.
--
-- `delivering` rows older than the stale window are reclaimed: a cron that is
-- killed mid-flight (timeout, deploy) would otherwise strand them forever.
CREATE OR REPLACE FUNCTION public.fn_webhook_claim_due(
  p_limit int DEFAULT 25,
  p_stale_minutes int DEFAULT 10
)
RETURNS SETOF public.webhook_deliveries
LANGUAGE sql VOLATILE SECURITY DEFINER SET search_path = public AS $$
  UPDATE public.webhook_deliveries d
     SET status = 'delivering',
         attempts = d.attempts + 1
   WHERE d.id IN (
     SELECT id FROM public.webhook_deliveries
      WHERE (status = 'queued' AND next_attempt_at <= now())
         OR (status = 'delivering' AND next_attempt_at < now() - (p_stale_minutes || ' minutes')::interval)
      ORDER BY next_attempt_at
      LIMIT p_limit
      FOR UPDATE SKIP LOCKED
   )
  RETURNING d.*;
$$;

-- 90-day retention, matching the routines dispatcher. Piggybacks the same cron.
CREATE OR REPLACE FUNCTION public.fn_webhook_prune(p_days int DEFAULT 90)
RETURNS integer
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = public AS $$
DECLARE n integer;
BEGIN
  DELETE FROM public.webhook_deliveries
   WHERE status IN ('done', 'error')
     AND created_at < now() - (p_days || ' days')::interval;
  GET DIAGNOSTICS n = ROW_COUNT;
  RETURN n;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.fn_webhook_claim_due(int, int) FROM anon, authenticated, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fn_webhook_prune(int)          FROM anon, authenticated, PUBLIC;
GRANT  EXECUTE ON FUNCTION public.fn_webhook_claim_due(int, int) TO service_role;
GRANT  EXECUTE ON FUNCTION public.fn_webhook_prune(int)          TO service_role;
